# Dark Sky weather tracking
- platform: darksky
  api_key: !secret dark_sky_api_key
  monitored_conditions:
    - summary
    - precip_type
    - precip_probability
    - temperature
    - humidity
    - temperature_max
    - temperature_min

# Plex num active users
- platform: plex
  host: !secret server_ip
  username: !secret plex_username
  password: !secret plex_password

# Xbox Live track my profile
- platform: xbox_live
  api_key: !secret xbox_live_api_key
  xuid:
    - !secret derek_xbox_xuid

# Tracks CPU speed for PI server
- platform: cpuspeed
  name: Raspberry Pi

# Weather Prediction
- platform: yr

# Google Maps travel times
- platform: google_travel_time
  name: Derek Work Commute
  api_key: !secret google_api_key
  origin: zone.derek_home
  destination: zone.derek_work

- platform: google_travel_time
  name: Derek Home Commute
  api_key: !secret google_api_key
  origin: zone.derek_work
  destination: zone.derek_home

# Owntracks Battery
- platform: mqtt
  state_topic: "owntracks/modphone"
  name: "Derek Phone Battery"
  qos: 0
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
