# 433 mhz rf light switches
- platform: rpi_rf
  name: Living Room
  gpio: 17
  switches:
    living_room_left:
      protocol: 1
      pulselength: 186
      code_on: 123456
      code_off: 123456
    living_room_right:
      protocol: 1
      pulselength: 186
      code_on: 123456
      code_off: 123456
    bedroom:
      protocol: 1
      pulselength: 186
      code_on: 123456
      code_off: 123456
    charging_stand:
      protocol: 1
      pulselength: 186
      code_on: 123456
      code_off: 123456
      